### PR TITLE
Add awesome badge

### PR DESCRIPTION
**Pull request by elrumordelaluz**
[Awesome](https://awesome.re)

### CODE REVIEW

**Comment by nucliweb** [comment]
Hi Lionel!
Thanks for the badge, **I like it!** 😊

You use an extension/plugin in your editor that change the markdown tables syntax, right?
I've got this extension a few months ago, but finally, I uninstall it because is difficult when you work in a small resolution.

Can you fix it and will send only the badge's code?

Thanks

**Comment by nucliweb** [comment]
Btw, just now I push a new version.
Can you pull the changes, please?

**Comment by elrumordelaluz** [comment]
oh, absolutely, I am sorry, probably prettier.

I’m now on mobile, will fix it as soon as I will be on desktop.


On 27 Oct 2018, at 14:07, Joan León <notifications@github.com<mailto:notifications@github.com>> wrote:


Btw, just now I push a new version.
Can you pull the changes, please?

**Comment by elrumordelaluz** [comment]
Must be _squashed_ :)

**Comment by nucliweb** [comment]
Thanks @elrumordelaluz 😊

**Pull request merged**
